# Generated by Django 2.1.7 on 2019-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190502_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='reply',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
